name: Deploy static content to Pages

on:
  # Trigger the workflow on push to the main branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Remove node_modules and package-lock.json to avoid dependency issues
      - name: Clean npm cache and install dependencies
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm cache clean --force
          npm install

      - name: Build project
        run: npm run build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
